import pytest
from unittest.mock import patch, MagicMock
from fastapi.testclient import TestClient
from api.server import app
from agent.chat_agent import get_chat_agent
from utils.db import ChatMessage

client = TestClient(app)

def test_chat_agent_initialization():
    agent = get_chat_agent()
    assert agent is not None

def test_chat_history_endpoint_empty():
    with patch("api.server.get_db") as mock_get_db:
        mock_db = MagicMock()
        mock_get_db.return_value = iter([mock_db])
        
        # Mock empty message history
        mock_db.query.return_value.filter_by.return_value.order_by.return_value.all.return_value = []
        
        response = client.get("/repos/owner/repo/chat/history", params={"session_id": "test_session"})
        assert response.status_code == 200
        assert response.json() == []

def test_chat_history_endpoint_with_data():
    with patch("api.server.get_db") as mock_get_db:
        mock_db = MagicMock()
        mock_get_db.return_value = iter([mock_db])
        
        msg1 = ChatMessage(role="user", content="Hello", session_id="test_session")
        msg2 = ChatMessage(role="assistant", content="Hi there!", session_id="test_session")
        
        mock_db.query.return_value.filter_by.return_value.order_by.return_value.all.return_value = [msg1, msg2]
        
        response = client.get("/repos/owner/repo/chat/history", params={"session_id": "test_session"})
        assert response.status_code == 200
        data = response.json()
        assert len(data) == 2
        assert data[0]["role"] == "user"
        assert data[0]["content"] == "Hello"
        assert data[1]["role"] == "assistant"
        assert data[1]["content"] == "Hi there!"

def test_chat_with_agent_route():
    import json
    with patch("api.server.get_db") as mock_get_db, \
         patch("api.server.get_onboarding_agent") as mock_get_agent:
         
        mock_db = MagicMock()
        mock_get_db.return_value = iter([mock_db, mock_db])
        
        # Mock agent stream response
        mock_agent = MagicMock()
        mock_agent.invoke_stream.return_value = iter([
            {"type": "thought", "content": "I am thinking...", "tool_calls": []},
            {"type": "token", "content": "Hello user, "},
            {"type": "token", "content": "I am your agent."},
            {"type": "final_answer", "content": "Hello user, I am your agent."},
            {"type": "final_state", "messages": []}
        ])
        mock_get_agent.return_value = mock_agent
        
        # Mock database messages list
        mock_db.query.return_value.filter_by.return_value.order_by.return_value.all.return_value = []
        
        payload = {
            "session_id": "test_session",
            "user_background": "I know Python",
            "message": "Explain the repository to me"
        }
        response = client.post("/repos/owner/repo/chat", json=payload)
        assert response.status_code == 200
        
        # Parse stream events
        events = []
        for line in response.iter_lines():
            if line.startswith("data: "):
                events.append(json.loads(line[6:]))
                
        final_answers = [e["content"] for e in events if e["type"] == "final_answer"]
        assert len(final_answers) > 0
        assert final_answers[0] == "Hello user, I am your agent."
        assert mock_db.add.called
        assert mock_db.commit.called

def test_prune_old_tool_results():
    from langchain_core.messages import HumanMessage, AIMessage
    from agent.chat_agent import prune_old_tool_results
    
    # Create a list of messages containing multiple tool results
    messages = [
        HumanMessage(content="User message"),
        AIMessage(content="Agent thought"),
        HumanMessage(content="TOOL RESULT: This is a very long result that we want to prune eventually. " * 10),
        AIMessage(content="Agent thought 2"),
        HumanMessage(content="TOOL RESULT: This is the second tool result.")
    ]
    
    pruned = prune_old_tool_results(messages, keep_last_n=1)
    
    # The first tool result should be truncated/pruned
    assert "truncated to save context window space" in pruned[2].content
    assert len(pruned[2].content) < 500
    
    # The second (most recent) tool result should NOT be pruned
    assert pruned[4].content == "TOOL RESULT: This is the second tool result."

def test_xml_parsing_robustness():
    import re
    
    # Test cases of different XML variations generated by LLMs
    test_cases = [
        # standard
        ("<tool_call><tool_name>list_github_directory</tool_name><tool_arg>src</tool_arg></tool_call>", "list_github_directory", "src"),
        # with tool_call_name
        ("<tool_call>\n<tool_call_name>list_github_directory</tool_call_name>\n<tool_arg></tool_arg>\n</tool_call>", "list_github_directory", ""),
        # with name / arg
        ("<tool_call><name>read_github_source_file</name><arg>api/server.py</arg></tool_call>", "read_github_source_file", "api/server.py"),
        # missing outer tool_call tag but containing name/arg
        ("<name>search_repo_issues_and_prs</name><arg>postgresql</arg>", "search_repo_issues_and_prs", "postgresql")
    ]
    
    for content, expected_name, expected_arg in test_cases:
        tool_name = None
        tool_arg = ""
        
        name_match = re.search(r"<(tool_name|tool_call_name|name)>(\w+)</\1>", content, re.IGNORECASE)
        if name_match:
            tool_name = name_match.group(2).strip()
            arg_match = re.search(r"<(tool_arg|arg)>(.*?)</\1>", content, re.DOTALL | re.IGNORECASE)
            if arg_match:
                tool_arg = arg_match.group(2).strip().strip('"').strip("'")
                
        assert tool_name == expected_name
        assert tool_arg == expected_arg


